### ISSUE TITLE
Use token in .env file instead

### ISSUE THREAD

**Issue by moghwan** [othmanelamnabhi/portfolio-thewannabedev#2]
Probably a typo since it's used in `getAllPostData` function, don't forget to regenerate it to deprecate the hard coded one.

https://github.com/othmanelamnabhi/portfolio-othmanelamnabhi/blob/f952e69692aca910ee93b3dfcc5b830fd45d157d/lib/posts.js#L35

**Comment by othmanelamnabhi** [comment]
Great catch, thanks Marwane, appreciate it 🙏
